services:
  md2img:
    image: ghcr.io/nemo1166/md2img:latest
    ports:
      - "${APP_PORT:-3921}:8000"
    volumes:
      - ./public:/app/public
    environment:
      - APP_PORT=${APP_PORT:-3921}
    restart: unless-stopped
